export const COURSES = [
  "Computer Science",
  "Software Engineering",
  "Data Structures and Algorithms",
  "Database Management",
  "Web Development",
  "Mobile App Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Networking",
  "Cloud Computing",
  "Big Data",
  "Blockchain Technology",
  "Internet of Things (IoT)",
  "DevOps",
  "Operating Systems",
  "Human-Computer Interaction",
  "Game Development",
  "Virtual Reality",
  "Data Science",
  "Data Analytics",
  "Information Systems",
  "Distributed Systems",
  "Systems Administration",
  "Digital Marketing",
];
